name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release for Deepin 23
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.25]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libgl1-mesa-dev \
            xorg-dev \
            libgtk-3-dev \
            build-essential

      - name: Get dependencies
        run: |
          go mod tidy

      - name: Build for Deepin 23
        run: |
          mkdir -p build
          env CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o build/system-monitor ./cmd/system-monitor/

      - name: Package as tar.gz
        run: |
          mkdir -p release
          tar -czf release/system-monitor-deepin23.tar.gz -C build system-monitor

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: System Monitor ${{ github.ref_name }} for Deepin 23
          body: |
            System Monitor for Deepin 23 Community Edition
            
            ## Installation
            1. Download system-monitor-deepin23.tar.gz
            2. Extract: `tar -xzf system-monitor-deepin23.tar.gz`
            3. Run: `./system-monitor`
            
            ## Usage
            - Left-click and drag to move the window
            - Right-click to close the application
            - Double-click to close the application
          files: |
            release/system-monitor-deepin23.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
