name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.25 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/system-monitor-linux-amd64 ./cmd/system-monitor/
          GOOS=linux GOARCH=arm64 go build -o build/system-monitor-linux-arm64 ./cmd/system-monitor/
          GOOS=darwin GOARCH=amd64 go build -o build/system-monitor-darwin-amd64 ./cmd/system-monitor/
          GOOS=darwin GOARCH=arm64 go build -o build/system-monitor-darwin-arm64 ./cmd/system-monitor/
          GOOS=windows GOARCH=amd64 go build -o build/system-monitor-windows-amd64.exe ./cmd/system-monitor/

      - name: Package
        run: |
          mkdir -p release
          tar -czf release/system-monitor-linux-amd64.tar.gz -C build system-monitor-linux-amd64
          tar -czf release/system-monitor-linux-arm64.tar.gz -C build system-monitor-linux-arm64
          tar -czf release/system-monitor-darwin-amd64.tar.gz -C build system-monitor-darwin-amd64
          tar -czf release/system-monitor-darwin-arm64.tar.gz -C build system-monitor-darwin-arm64
          zip -j release/system-monitor-windows-amd64.zip build/system-monitor-windows-amd64.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/system-monitor-linux-amd64.tar.gz
            release/system-monitor-linux-arm64.tar.gz
            release/system-monitor-darwin-amd64.tar.gz
            release/system-monitor-darwin-arm64.tar.gz
            release/system-monitor-windows-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
